In [1]:
# E-commerce Sales Data Cleaning & Analysis

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("ecommerce_sales_dataset.csv")
df = df.replace({np.nan: None})
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,Age,City,State,Region,Product_ID,Product_Category,Product_Name,Quantity,Price,Discount,Sales,Profit,Payment_Mode,Delivery_Status,Feedback_Rating
0,ORD100000,2026-02-02,CUST3275,Monica Long,Male,60,Ericfort,Tennessee,South,PROD364,Furniture,Appear,10,371.29,0.24,500.87,-61.79,UPI,Cancelled,2
1,ORD100001,2025-01-15,CUST5856,Alfred Reeves,Male,46,Williamsville,Pennsylvania,East,PROD205,Clothing,Either,10,72.62,0.14,154.52,-51.02,Card,Delivered,1
2,ORD100002,2025-11-15,CUST2135,Brian Johnston,Female,55,New Stephanieton,Missouri,South,PROD436,Food,Miss,6,454.08,0.21,955.17,205.61,UPI,Pending,2
3,ORD100003,2024-07-29,CUST1959,Jeffrey Allison,Male,55,Port Jessicaburgh,Kentucky,North,PROD806,Furniture,Thus,1,399.96,0.15,146.52,-94.93,Cash,Cancelled,1
4,ORD100004,2026-02-21,CUST6626,Kathleen Lopez,Male,27,Trevorland,Arizona,West,PROD796,Furniture,When,10,318.98,0.19,149.62,-62.00,Cash,Delivered,1

In [15]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order_ID          100000 non-null  object
 1   Order_Date        100000 non-null  object
 2   Customer_ID       100000 non-null  object
 3   Customer_Name     100000 non-null  object
 4   Gender            100000 non-null  object
 5   Age               100000 non-null  int64
 6   City              100000 non-null  object
 7   State             100000 non-null  object
 8   Region            100000 non-null  object
 9   Product_ID        100000 non-null  object
 10  Product_Category  100000 non-null  object
 11  Product_Name      99888 non-null   object
 12  Quantity          100000 non-null  int64
 13  Price             100000 non-null  float64
 14  Discount          100000 non-null  float64
 15  Sales             100000 non-null  float64
 16  Profit            100000 non-null  float64
 17  Payment_Mode      100000 non-null  object
 18  Delivery_Status   100000 non-null  object
 19  Feedback_Rating   100000 non-null  int64
dtypes: float64(4), int64(3), object(13)
memory usage: 15.3+ MB

,Age,Quantity,Price,Discount,Sales,Profit,Feedback_Rating
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.487710,5.506890,255.519091,0.150418,511.404936,99.028766,2.999530
std,13.830917,2.875544,141.502710,0.086738,283.375702,115.401880,1.415108
min,18.000000,1.000000,10.000000,0.000000,20.000000,-99.990000,1.000000
25%,30.000000,3.000000,132.937500,0.080000,265.320000,-1.020000,2.000000
50%,41.000000,6.000000,255.620000,0.150000,511.645000,98.560000,3.000000
75%,53.000000,8.000000,378.340000,0.230000,758.342500,198.540000,4.000000
max,65.000000,10.000000,500.000000,0.300000,999.980000,300.000000,5.000000

In [16]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df.drop_duplicates(inplace=True)
df.fillna(0, inplace=True)

In [17]:
df['Month'] = df['Order_Date'].dt.month
df['Year'] = df['Order_Date'].dt.year

df['Profit_Margin'] = df.apply(
    lambda x: x['Profit']/x['Sales'] if x['Sales'] != 0 else 0, axis=1
)

df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,Age,City,State,Region,Product_ID,...,Price,Discount,Sales,Profit,Payment_Mode,Delivery_Status,Feedback_Rating,Month,Year,Profit_Margin
0,ORD100000,2026-02-02,CUST3275,Monica Long,Male,60,Ericfort,Tennessee,South,PROD364,...,371.29,0.24,500.87,-61.79,UPI,Cancelled,2,2,2026,-0.123365
1,ORD100001,2025-01-15,CUST5856,Alfred Reeves,Male,46,Williamsville,Pennsylvania,East,PROD205,...,72.62,0.14,154.52,-51.02,Card,Delivered,1,1,2025,-0.330184
2,ORD100002,2025-11-15,CUST2135,Brian Johnston,Female,55,New Stephanieton,Missouri,South,PROD436,...,454.08,0.21,955.17,205.61,UPI,Pending,2,11,2025,0.215260
3,ORD100003,2024-07-29,CUST1959,Jeffrey Allison,Male,55,Port Jessicaburgh,Kentucky,North,PROD806,...,399.96,0.15,146.52,-94.93,Cash,Cancelled,1,7,2024,-0.647898
4,ORD100004,2026-02-21,CUST6626,Kathleen Lopez,Male,27,Trevorland,Arizona,West,PROD796,...,318.98,0.19,149.62,-62.00,Cash,Delivered,1,2,2026,-0.414383

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Kachhua_Kachhwi@2428",
    database="project_db"
)

print("Connected")

In [1]:
!pip uninstall mysql-connector-python -y

Found existing installation: mysql-connector-python 9.7.0
Uninstalling mysql-connector-python-9.7.0:
  Successfully uninstalled mysql-connector-python-9.7.0

In [2]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Using cached mysql_connector_python-9.7.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Using cached mysql_connector_python-9.7.0-cp311-cp311-win_amd64.whl (17.7 MB)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [1]:
import mysql.connector
print("import ok")

import ok

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Kachhua_Kachhwi@2428"
)

print("✅ Connected to MySQL Server")

In [1]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.3 kB ? eta -:--:--
   ------------------ --------------------- 20.5/45.3 kB 682.7 kB/s eta 0:00:01
   ---------------------------------------- 45.3/45.3 kB 762.2 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [1]:
import pymysql

conn = pymysql.connect(
    host="localhost",
    user="root",
    password="Kachhua_Kachhwi@2428",
    database="project_db"
)

print("✅ Connected successfully")

✅ Connected successfully

In [2]:
cursor = conn.cursor()
cursor.execute("SHOW TABLES")

for table in cursor.fetchall():
    print(table)

('customers',)
('order_details',)
('orders',)
('products',)

In [3]:
cursor.execute("SELECT COUNT(*) FROM orders")
print(cursor.fetchone())

(0,)

In [4]:
cursor = conn.cursor()

In [9]:
customers = df[['Customer_ID','Customer_Name','Gender','Age','City','State','Region']].drop_duplicates()

for _, row in customers.iterrows():
    cursor.execute("""
    INSERT IGNORE INTO customers 
    (customer_id, customer_name, gender, age, city, state, region)
    VALUES (%s,%s,%s,%s,%s,%s,%s)
    """, tuple(row))

conn.commit()
print("Customers loaded")

Customers loaded

In [18]:
products = df[['Product_ID','Product_Category','Product_Name','Price']].drop_duplicates()

for _, row in products.iterrows():
    cursor.execute("""
    INSERT IGNORE INTO products
    (product_id, product_category, product_name, price)
    VALUES (%s,%s,%s,%s)
    """, tuple(row))

conn.commit()
print("Products loaded")

Products loaded

In [11]:
products = df[['Product_ID','Product_Category','Product_Name','Price']].drop_duplicates()

products = products.where(pd.notnull(products), None)

In [19]:
products = df[['Product_ID','Product_Category','Product_Name','Price']].drop_duplicates()

for _, row in products.iterrows():
    cursor.execute("""
    INSERT IGNORE INTO products
    (product_id, product_category, product_name, price)
    VALUES (%s,%s,%s,%s)
    """, tuple(row))

conn.commit()
print("✅ Products loaded")

✅ Products loaded

In [20]:
orders = df[['Order_ID','Order_Date','Customer_ID','Payment_Mode','Delivery_Status']].drop_duplicates()

for _, row in orders.iterrows():
    cursor.execute("""
    INSERT IGNORE INTO orders
    (order_id, order_date, customer_id, payment_mode, delivery_status)
    VALUES (%s,%s,%s,%s,%s)
    """, tuple(row))

conn.commit()
print("✅ Orders loaded")

✅ Orders loaded

In [21]:
order_details = df[['Order_ID','Product_ID','Quantity','Discount','Sales','Profit','Feedback_Rating']]

for _, row in order_details.iterrows():
    cursor.execute("""
    INSERT INTO order_details
    (order_id, product_id, quantity, discount, sales, profit, feedback_rating)
    VALUES (%s,%s,%s,%s,%s,%s,%s)
    """, tuple(row))

conn.commit()
print("✅ Order Details loaded")

✅ Order Details loaded

In [22]:
cursor.execute("SELECT COUNT(*) FROM customers")
print("Customers:", cursor.fetchone())

cursor.execute("SELECT COUNT(*) FROM orders")
print("Orders:", cursor.fetchone())

Customers: (9000,)
Orders: (100000,)